name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: get Go version
      run: |
        go_version=$(cat go.mod | grep "^go" | cut -d ' ' -f 2)
        echo "go_version=${go_version}" >> $GITHUB_ENV
    - name: print go version
      run: |
        echo ${{ env.go_version }}
        

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        # go-version: 1.16
        go-version: ${{ env.go_version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
